# Generated by Django 5.0.1 on 2024-10-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('designation', models.CharField(max_length=255)),
                ('facebook', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
            ],
        ),
    ]
